config/routes.rb
Rails.application.routes.draw do
 root "home#top"
 get "/about", to: "home#about"
 get    '/login',   to: 'sessions#new'
 post   '/login',   to: 'sessions#create'
 delete '/logout',  to: 'sessions#destroy'
 resources :users
 resources :posts do
   resources :comments
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true,length:{maximum:200}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true,length:{maximum:1000}
  paginates_per 10
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :set_current_user

   def set_current_user
    @current_user = User.find_by(id: session[:user_id])
   end
   
  def authenticate_user
    if @current_user == nil
      flash[:danger] = "ログインが必要です"
      redirect_to login_path
    end
  end
  
   def forbid_login_user
    if @current_user
      flash[:danger] = "すでにログインしています"
      redirect_to posts_path
    end
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 before_action :authenticate_user
 
 def create
   @post = Post.find(params[:post_id])
   @comment = Comment.new(comment_params)
   @comments = Comment.where(post_id: @post.id)
   if @comment.save
     flash[:success] = "コメントしました"
     redirect_to post_path(@post)
   else
     flash[:danger] = "コメントできませんでした"
     render "posts/show"
   end
 end
 
 private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: @current_user.id,post_id: params[:post_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user,{only: [:edit,:destroy,:new,:create]}
before_action :ensure_correct_user,{only: [:edit, :update, :destroy]}


  def index
     @search = Post.ransack(params[:q])
     @posts = @search.result.page(params[:page])
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
    @comments = Comment.where(post_id: @post.id)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to posts_url
  end
  
  def update
     @post = Post.find(params[:id])
     if @post.update(post_params)
      flash[:success] = "投稿が編集されました"
      redirect_to @post
     else
      flash[:danger] = "投稿できませんでした"
      render "edit"
     end
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = @current_user.id
   if @post.save
      flash[:success] = "投稿を作成しました"
      redirect_to posts_url
   else
      flash[:danger] = "投稿できませんでした"
      render "new"
   end
  end
  
  def  ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != @current_user.id && !@current_user.admin?
      flash[:danger] = "権限がありません"
      redirect_to posts_path
    end
  end



  private
  
    def post_params
      params.require(:post).permit(:content,:tag_id,:anonymous_check)
    end
  
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      flash[:success] = "ログインしました"
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:danger] = 'メールアドレスまたはパスワードが間違っています'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update, :show]}
  before_action :admin_user,{only: [:index,:destroy]}
  
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts.page(params[:page]).per(10)
  end

  def index
    @users = User.page(params[:page]).per(30)
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "ユーザー登録が完了しました"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def update
     @user = User.find(params[:id])
     if @user.update(user_params)
      flash[:success] = "プロフィールが更新されました"
      redirect_to @user
     else
      render 'edit'
     end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーが削除されました"
    redirect_to users_path
  end
  
  def ensure_correct_user
    if @current_user.id != params[:id].to_i && !@current_user.admin
      flash[:danger] = "権限がありません"
      redirect_to posts_path
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
    
    
    def admin_user
       unless @current_user.admin?
         flash[:danger] = "管理者権限がありません"
         redirect_to posts_path
       end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="about-main">
  <h2>MoreHelpとは</h2>
  <p class = "text-center">
    MoreHelpは多くの人の悩みを解決したいという思いから作られました.<br>
    気軽になんでも投稿してください。
  </p>
</div>

app/views/home/top.html.erb
<div class="center jumbotron">
  <h1>ようこそMoreHelpへ</h1>
  
　<h2>MoreHelpは、お気軽にお悩み相談ができるサイトです。</h2>
  <h2>まずは登録して、お悩みを相談してみましょう。</h2>
  

  <%= link_to "登録する", new_user_path , class: "btn btn-lg btn-primary" %>
</div>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-default" >
  <div class="container">
    <%= link_to "MoreHelp", root_path ,id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if @current_user%>
        <li>
         <% if @current_user.admin?%>
          <%= link_to "登録者一覧", users_path %>
         <% else %>
          <%= link_to @current_user.name,user_path(@current_user.id) %>
         <% end %>
        </li>
        <li>
          <%= link_to "投稿一覧", posts_path %>
        </li>
        <li>
          <%= link_to "新規投稿", new_post_path, data: {"turbolinks" => false} %>
        </li>
        <li>
          <%= link_to "ログアウト", logout_path, method: :delete %>
        </li>
        <% else %>
        <li>
          <%= link_to "MoreHelpとは", about_path %>
        </li>
        <li>
          <%= link_to "投稿一覧", posts_path %>
        </li>
        <li>
          <%= link_to "新規登録", new_user_path %>
        </li>
        <li>
          <%= link_to "ログイン", login_path %>
        </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoreHelp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  </head>
  <body>
    <div>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    </div>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">編集する(1000字以内)</h1>
      <%= form_for(@post) do |f| %>
        <div class="form-group">
          <%= f.text_area :content,class: 'form-control  js-text', placeholder: "ここに内容を入力してください..." %>
        </div>
        <P class="js-text-count pull-right"></P>
        <div class="text-warning">
        <%= f.label :tag_id,"カテゴリーを指定してください" %>
         </div>
        <%= f.select :tag_id, [['恋愛', 1], ['人間関係', 2], ['勉強', 3],['仕事',4],['学校',5],['身体',6],['その他',7]],
        {include_blank: '指定しない'}, class: 'tag' %>
        
      
        <%= f.label :anonymous_check, class: "checkbox inline" do %>
        <%= f.check_box :anonymous_check %>
        <span>匿名で投稿する場合は、ここにチェックを入れてください</span>
        <% end %>
      <%= f.submit "投稿を編集する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <%= search_form_for @search do |f| %>
      <%= f.search_field :content_cont, placeholder: "検索したいキーワードを入れてください" %>
      <%= f.select :tag_id_eq, [['恋愛', 1], ['人間関係', 2], ['勉強', 3],['仕事',4],['学校',5],['身体',6],['その他',7]] , prompt: "カテゴリーを選んでください"%>
       <%= f.submit %>
      <% end %>
    <p class = "posts-list">投稿一覧</p>
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <div class="post-right">
          <%= link_to truncate(post.content,length:100), post, data: {"turbolinks" => false} %>
        </div>
      </div>
    <% end %>
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿する(1000字以内)</h1>
      <%= form_for(@post) do |f| %>
        <div class="form-group">
          <%= f.text_area :content,class: 'form-control  js-text', placeholder: "ここに内容を入力してください..." %>
        </div>
        <P class="js-text-count pull-right"></P>
        <div class="text-warning">
        <%= f.label :tag_id,"カテゴリーを指定してください" %>
         </div>
        <%= f.select :tag_id, [['恋愛', 1], ['人間関係', 2], ['勉強', 3],['仕事',4],['学校',5],['身体',6],['その他',7]],
        {include_blank: '指定しない'}, class: 'tag' %>
      
        <%= f.label :anonymous_check, class: "checkbox inline" do %>
        <%= f.check_box :anonymous_check %>
        <span>匿名で投稿する場合は、ここにチェックを入れてください</span>
        <% end %>
      <%= f.submit "投稿する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <p>
        <% if @post.anonymous_check %>
         匿名　さん
        <% else %>
        <%= @post.user.name %>　さん
        <% end %>
      </p>
      <p>
        <%= simple_format(@post.content) %>
      </p>
      <div class="post-time">
        <%= "投稿日時: #{@post.created_at.to_s(:datetime_jp)}" %>
      </div>
        <div class="post-menus">
       <% if @current_user == nil%>
       
       <% elsif @current_user.admin?%>
        <%= link_to "削除", post_path(@post), method: :delete %>
       <% elsif @post.user_id == @current_user.id %>
        <%= link_to "編集", edit_post_path(@post), data: {"turbolinks" => false} %>
        <%= link_to "削除", post_path(@post), method: :delete %>
       <% end %>
       </div>
      </div>
     <% if @current_user == nil %>
      <p class = "comment-show">コメントするにはログインしてください</p>
    <% else %>
      <p class = "comment-show">コメントする(300字以内)</p>
        <%= form_for [@post, @comment] do |f| %>
  　　      <div class="form-group">
    　　      <%= f.text_area :content,class: 'form-control  js-comment ', placeholder: "ここにコメントしてください" %>
  　　      </div>
  　　      <P class="js-comment-count pull-right"></P>
  　     <%= f.submit "コメントする", class: "btn btn-primary" %>
　　  <% end %>
　　<% end %>
   <div class="posts-show-item">
    <li>コメント一覧</li>
    　<% @comments.each do |comment|%>
    　<% if @post.user.name == comment.user.name && @post.anonymous_check %>
    　   <h3 class="text-danger">匿名 さん</h3>
    　 <% elsif @post.user.name == comment.user.name %>
    　   <h3 class="text-danger"><%= comment.user.name %> さん</h3>
    　 <% else %>
    　   <h4><%= comment.user.name %> さん</h4>
    　 <% end %>
    　 <%= simple_format(comment.content) %>
    　  <div class="post-time">
        <%= "投稿日時: #{comment.created_at.to_s(:datetime_jp)}" %>
      </div>
    <% end %>
    　</div>
   </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      このフォームには <%= pluralize(@user.errors.count, "つのエラーがあります") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">アカウント編集</div>
    <div class="form users-form">
      <div class="form-body">
        <div class="text-warning">
        <%= render 'shared/error_messages' %>
        
        <%= form_for(@user) do |f| %>
        <%= f.label :name,"ユーザー名を変更する" %>
        <%= f.text_field :name,class: 'form-control' %>
        <%= f.label :password,"パスワードを変更する" %>
        <%= f.password_field :password,class: 'form-control' %>
        <%= f.submit "変更を保存する", class: "btn btn-primary" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
 <div class="main posts-index">
  <div class="container">
 <p class="posts-list">登録者一覧</p>
    <% @users.each do |user| %>
      <div class="posts-index-item">
        <div class="post-right">
         ユーザー名： <%=link_to user.name,user %>　
            <% if @current_user.admin? && user != @current_user  %>
              <%= link_to "削除", user, method: :delete,
                                  data: { confirm: "本当に削除してもよろしいですか?" },
                                  class: "pull-right"%>
            <% end %>
        </div>
      </div>
    <% end %>
    <%= paginate @users %>
  </div>
  </div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-warning">
        <%= render 'shared/error_messages' %>
         
        <%= form_for(@user) do |f| %>
        
        <%= f.label :name, "ユーザー名" %>
        <%= f.text_field :name, class: 'form-control' %>
        
        <%= f.label :email, "メールアドレス"%>
        <%= f.email_field :email, class: 'form-control'%>
        
        <%= f.label :password, "パスワード(８文字以上)" %>
        <%= f.password_field :password,class: 'form-control' %>
        
        <%= f.submit "新規登録する", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <h2>ユーザー名：
        <%= @user.name %>
      </h2>
      <h2>メールアドレス：
        <%= @user.email %>
      </h2>
      <% if @user.id == @current_user.id %>
      <%= link_to "編集", edit_user_path(@user) %>
      <% end %>
          </div>
      </div>
    </div>
      <div class="main posts-index">
        <div class="container">
          <h2 class="posts-list">自分の投稿</h2>
          <% if  @posts.length == 0 %>
           <h2 class="text-center text-danger">投稿がありません</h2>
          <% end %>
          <% @posts.each do |post| %>
          <div class="posts-index-item">
            <div class="post-right">
              <%= link_to truncate(post.content,length:100), post, data: {"turbolinks" => false} %>
            </div>
          </div>
          <% end %>
          <%= paginate @posts %>
  </div>
</div>